### ISSUE TITLE
Studio di Fattibilità

### ISSUE THREAD

**Issue by gallizzz** [LorenzoGallizioli/WireShield#1]
Stilare uno studio di fattbilità per il progetto

**Comment by paganello** [comment]
realizzato e caricato nal main

**Comment by bnsdavide03** [comment]
@paganello ho notato alcune imprecisioni nelle modifiche documento.
Te le ho scritte su whatsapp con tanto di foto.

**Comment by paganello** [comment]
Egregio, magifico, ing. Bonsembiante (@bnsdavide03); ho sistemato le imprecisioni da lei riportate.
A nome di tutto lo staff tecnico la ringrazio del suo contributo a questo progetto.
Nell'augurio di una buona permanenza su questo pianeta, le auguro una buona serata.

TP
