### ISSUE TITLE
Consegna ProjectPlan

### ISSUE THREAD

**Issue by paganello** [LorenzoGallizioli/WireShield#27]
Con questa issue provvediamo a consegnare il project plan per la revisione.

ProjectPlan: https://github.com/LorenzoGallizioli/WireShield/blob/main/ProjectPlan.md

**Comment by garganti** [comment]
Ho qualche dubbio per il vostro progetto per funzionare abbia bisogno di software extra  ... un requisito del progetto è quello che funzioni a se stante. Non va neanche bene che voi diate i binari - indicate invece quali software uno deve installare per poi far funzionare il vostro progetto. - tipo un manuale di installazione (normalmente non richiesto). Non si può fare a meno del software eterno e usare invece libreria java per l'antivirus e la vpn?

**Comment by garganti** [comment]
Ok, ho letto la fattibilità e capisco. Approvo ma con qualche dubbio che rimane che poi io riesca ad eseguirlo sul mio PC senza rischi.

**Comment by gallizzz** [comment]
Buongiorno, siamo consapevoli del fatto che ciò da lei citato non sia ottimale per il funzionamento del programma. 
Ci stiamo attualmente lavorando e siamo riusciti ad implementare con successo metodi per limitare la cosa e cercare di proporre una soluzione integrata limitando al massimo la dipendenza da software terzi.
Grazie per il feedback!
