### ISSUE TITLE
Implementazione classi DownloadMonitor, File & AntivirusManager

### ISSUE THREAD

**Issue by paganello** [LorenzoGallizioli/WireShield#30]
## Implementare DownloadMonitor, File & AntivirusManager

Si richiede, come concordato, l'implementazione delle classi sopra elencate. completare l'inegrazione delle stesse nella classe di gestione ```SystemOrchestarator```.

**Comment by bnsdavide03** [comment]
Ho finito di inserire log4j, Domani mi sa che feve guardare dei pontfiirtti tr"  log4jy

**Comment by paganello** [comment]
Ho preso visione del lavoro svolto. faccio anche a te i complimenti per il lavoro svolto e approvo il merge.
Unica nota ti chiedo di rimuovere i main di test commentati che hai inserito in coda alle classi, intanto hai gia realizzato le classi di test.
