### ISSUE TITLE
Eliminare dipendenza ciclica presente tra com.wireshield.av e com.wireshield.localfileutils

### ISSUE THREAD

**Issue by bnsdavide03** [LorenzoGallizioli/WireShield#43]
## TASK
Dopo il merging del branch #42 bisogna togliere la dipendenza ciclica tra com.wireshield.av e com.wireshield.localfileutils dovuta più precisamente da due metodi di virustotal che usufruiscono dei metodi in FileManager.
Possibile soluzione: spostare System Orchestrator insieme alla classe per la gui e rinominare in fine il package con un nome più consono.

**Comment by bnsdavide03** [comment]
Durante i test effettuati per individuare possibili soluzioni al problema della dipendenza ciclica tra i package, ho riscontrato che una combinazione potenzialmente efficace potrebbe essere quella di spostare AntivirusManager e VirusTotal in localutils. Tuttavia, considero questa soluzione poco appropriata, in quanto raggruppa classi che non sono coerenti con la propria categoria.

Dato che questa issue richiede decisioni importanti riguardanti l'organizzazione e la rinominazione dei package, propongo di affrontarla durante lo Sprint Backlog. In questo modo, potremo prendere insieme tutte le decisioni necessarie in un'unica sessione, garantendo maggiore coerenza e condivisione. 👍🏻

**Comment by paganello** [comment]
Ho brevemente riflettuto sul problema e sulle possibili soluzioni, credo che la strada piu adatta si a creare un nuovo package che contenga solo ed esclusivamente la classe FileManager. Cio comportarebbe la necessita di rinominare il package localfileutils per garantire coerenza nella nomenclatura.

**Comment by bnsdavide03** [comment]
Completato durante lo Scrum Week della giornata odierna!

**Comment by bnsdavide03** [comment]
Completato durante lo Scrum Week della giornata odierna!
