### ISSUE TITLE
Richiesta di verifica correttezza + test per la classe VirusTotal

### ISSUE THREAD

**Issue by paganello** [LorenzoGallizioli/WireShield#52]
Ho aggiornato la classe (sostitutendo anche i syso con i piu corretti logger e modificando alcuni testi stampati dai log) abilitandola all'utilizzo dei nuovi metodi di ```FileManager``` dedicati alla letture a ggionrmaneto del file JSON contenente le configurazioni del progetto.

**Dato che sei tu che hai realizzato la classe ti chiedo di eseguire una review (anche test di esecuzione se riesci)**
#53

**Comment by bnsdavide03** [comment]
Fatto, ti ho risposto direttamente nel branch #53 👍🏻
