### ISSUE TITLE
Revisione e continuazione del Project Plan

### ISSUE THREAD

**Issue by paganello** [LorenzoGallizioli/WireShield#9]
io e @bnsdavide03 abbiamo realizzato una parte del project plan, sarebbe utile andare avanti e ultimarne la stesura.

**Comment by gallizzz** [comment]
## Checkpoint 15/11/2024
23:15 - Terminata la sessione di oggi di redazione in coppia del project plan (7 ore).
Abbiamo raggiunto il capitolo _Garanzie di Qualità_, si ipotizzano circa 3 ore per terminare totalmente il piano. 
Chiedo a @paganello se possibile di dare un occhio in particolare agli strumenti di test che abbiamo indicato, soprattutto per GUI, dato che non eravamo convinti delle opzioni. Attendiamo qualche commento in merito.
